---
# Install custom system packages
# The following will be installed by hand
# but dependencies may be installed here
# - Ansible
# - Emacs
# - Vagrant
- hosts: all
  tasks:
    - name: Install Basic Packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
        autoremove: yes
        cache_valid_time: 86400
      with_items:
        - vlc
        - git
        - python-pip
        - nfs-kernel-server
        - traceroute
        - cheese
        - libedit-dev
        - nethogs
        - redshift
        - redshift-gtk
        - xclip
        - cryptsetup
        - graphviz
        - whois
        - valgrind
        - clamav-daemon
        - clamav
        - rkhunter
        - tiger
        - gimp
        - macchanger
        - ngrep
        - lxc
        - wireshark
        - python-dev
        - python3-dev
        - calibre
        - android-tools-adb
        - chromium-browser
        - unrar
        - gparted
        - virtualbox

    - name: Install general Python deps
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
        - virtualenv
        - flake8
        - jedi
        - coverage
